### ISSUE TITLE
Master issue do v1

### ISSUE THREAD

**Issue by chicodias** [chicodias/ipeadatar-shiny#1]
Os itens dessa lista serão atualizados ao longo do tempo e contém diferentes itens de ação para o projeto em shiny.

# Inputs: 
 - [x] Label com mais detalhes da série (como os valores dos filtros abaixo)
 - [x] Filtros
   - [x] Slider de data (período de dias a ser mostrado nos gráficos)
   - [x] Frequencia
   - [x] Temas
   - [x] Status
   - [x] Source

# Transformações
 - [x] Logaritmica
 - [x] Box-Cox

# Gráficos
 - [x] Auto correlação
 - [x] Gráficos no plotly
 - [x] ... 

# Modelagem
 - [x] Criar modelo 
 - [x] Sazonalidade

# Diagnóstico
 - [x] Resíduos
